name: GitHub Actions Demo App

on:
    push:
      branches: [main]

jobs:
  unit-tests:
    name: Run Test On PR
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_15.3.app

    - name: Build
      run: xcodebuild -scheme MyApplication -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4'

    - name: Run Tests
      run: xcodebuild -scheme MyApplication -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' test
